/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountGetAccountFees } from "../../funcs/accountGetAccountFees.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$accountGetAccountFees: ToolDefinition = {
  name: "account-get-account-fees",
  description: `Obter taxas da conta`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accountGetAccountFees(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
