/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountGetAccountBalance } from "../../funcs/accountGetAccountBalance.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$accountGetAccountBalance: ToolDefinition = {
  name: "account-get-account-balance",
  description: `Obter saldo da conta`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accountGetAccountBalance(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
