/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountGetAccount } from "../../funcs/accountGetAccount.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$accountGetAccount: ToolDefinition = {
  name: "account-get-account",
  description: `Obter informações da conta`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accountGetAccount(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
