/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountGetAccount } from "../funcs/accountGetAccount.js";
import { accountGetAccountBalance } from "../funcs/accountGetAccountBalance.js";
import { accountGetAccountFees } from "../funcs/accountGetAccountFees.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Account extends ClientSDK {
  /**
   * Obter informações da conta
   */
  async getAccount(
    options?: RequestOptions,
  ): Promise<components.Account> {
    return unwrapAsync(accountGetAccount(
      this,
      options,
    ));
  }

  /**
   * Obter saldo da conta
   */
  async getAccountBalance(
    options?: RequestOptions,
  ): Promise<components.AccountBalance> {
    return unwrapAsync(accountGetAccountBalance(
      this,
      options,
    ));
  }

  /**
   * Obter taxas da conta
   */
  async getAccountFees(
    options?: RequestOptions,
  ): Promise<components.AccountFees> {
    return unwrapAsync(accountGetAccountFees(
      this,
      options,
    ));
  }
}
