/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Account } from "./account.js";

export class Payle extends ClientSDK {
  private _account?: Account;
  get account(): Account {
    return (this._account ??= new Account(this._options));
  }
}
